# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := klee
PROJ_VERSION := 0.01

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/wei/Documents/code/klee2.7/llvm-2.7

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/wei/Documents/code/klee2.7/llvm-2.7

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/wei/Documents/code/klee2.7/klee)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,@abs_top_objdir@)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

ENABLE_EXT_STP := 1
STP_ROOT := /home/wei/Documents/code/klee2.7/stp/stp/install

ENABLE_POSIX_RUNTIME := 1
ENABLE_STPLOG := @ENABLE_STPLOG@
ENABLE_UCLIBC := 1

HAVE_SELINUX := 0

RUNTIME_ENABLE_OPTIMIZED := 1
RUNTIME_DISABLE_ASSERTIONS :=
RUNTIME_ENABLE_COVERAGE :=
RUNTIME_ENABLE_PROFILING :=

# A list of "features" which tests can check for in XFAIL:
TEST_FEATURE_LIST :=

ifeq ($(HAVE_SELINUX_SELINUX_H),1)
  TEST_FEATURE_LIST += have-selinux
else
  TEST_FEATURE_LIST += no-selinux
endif

CFLAGS := -g -O2
CXXFLAGS := -g -O2
LDFLAGS := 
